name: Label Issues by Priority

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  priority:
    uses: Orka-Informatika/.github/.github/workflows/issue-priority.yml@500ae14dd0fd76f84157d6d54fdf0bb5dcb1599d
