name: Label Issues by Priority

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  priority:
    uses: Orka-Informatika/.github/.github/workflows/issue-priority.yml@stable
